name: CI Tests

on:
  push:
    branches:
      - "**"

jobs:
  test-cluster:
    name: "Test cluster (no mergers)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest .
      - name: Test cluster
        run: python -m pytest tests/test_cluster.py -v

  test-mergers:
    name: "Test mergers"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest .
          pip install surfinBH bhptnrremnant h5py lalsuite


      - name: Test mergers
        run: python -m pytest tests/test_merger.py -v