name: CI Tests

on:
  push:
    branches:
      - "**"

jobs:
  test-clusterbh:
    name: "Test clusterBH"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test clusterBH
        run: python -m pytest tests/test_clusterbh.py -v

  test-bhbdynamics:
    name: "Test BHBdynamics"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest .

      - name: Test BHBdynamics
        run: python -m pytest tests/test_bhbdynamics.py -v